feature: Add multiple choice function
Leshangpang/COMP30022-SDGs-Frontend pull request #23
Opened 2024-09-13 02:22 UTC by Wj12344

This component, `MultipleChoice`, is designed for a quiz or questionnaire interface. It displays a series of questions where users can select answers. The component includes navigation buttons to move between questions and a progress bar showing the current position. Users can submit their answers once all questions are answered. After submission, a confirmation dialog appears, and upon confirmation, a success message is displayed, and the interface switches to a completion view. The component also ensures users cannot proceed to the next question without selecting an answer.

2024-09-14 01:18 UTC, YuetongLiiii requested changes
For flashcard: The story of Alice is a good idea to attract students. However,  I think we need to adjust the layout, because current layout is the story is below the flashcard, it's quiet wired for user to scroll to look the introduction and story. How about Put the whole story on the first page of the flashcard, and then explain that clicking the button on the right will start the flashcard. I think this layout will look better. Secondly, I think the background of the buttons on the left and right should be white instead of transparent, because they are hard to find. I think making the buttons more eye-catching can improve the user experience.

For quiz: I think we need to increase the transparency of the options. The current buttons have backgrounds that can be seen. If we add text and pictures later, it will look a bit messy. We can change the color of the options to a lighter color, such as light pink.

Another suggestion is that I think it is best to modify different functions in different branches. If you modify multiple functions in one branch, if a pull request for one of the functions cannot be passed, you still have to do some deletion work. This will make it more difficult to merge to main.

2024-09-16 05:40 UTC, Leshangpang requested changes
Please delete files (images) that are no longer being used. 
And what does it mean by AskMenu and EachGoalBar? Can you please rename for better clarity i.e. start the name with the page that uses this component. 
For both the flashcard and the quiz page, I think it would look nicer to add more space between around the content (between the banner and content, on the left, right, bottom etc.) for more breathability. 
For the question for quiz, I think the letters can be much larger to make the question more obvious and stand out. The same goes for the options. The main focus of the page should be on the question and not the background image or anything else. 
And for the colour of buttons, I highly suggest using the colours from the palette that we have selected. Please don't add anymore new colours to the ones that we already have as we want to keep the theme of the website consistent.

2024-09-16 05:40 UTC, Leshangpang commented on itp-front/src/assets/image/222.png
Is this image really relevant to the goal of gender equality? Because I think it is more to do with gender identity.

2024-09-16 05:40 UTC, Leshangpang commented on itp-front/src/assets/image/222.png
Also, please rename the file for better clarity.

2024-09-16 05:40 UTC, Leshangpang commented on itp-front/src/assets/image/Goal5 flash_card_bg.jpg
Where is this picture used? Please remove if it is no longer needed.

2024-09-16 06:00 UTC, Leshangpang commented
Note: remember format for commit messages. It is TASK-xxx.

2024-09-16 07:10 UTC, merged